# -*- coding: utf-8 -*-
"""Day1_Python_Basics.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6OkIc_caVtqnp4367lX6esvpJi3MeW_

# Basic Python
"""

# printing statements
print("hii,I am Himani")
print("I am 20 yrs old")
print("I am studying python basics")
print("I am in learning mode")

# variables
name = " himani"
age = 20
height = 5.3
cgpa = 8.8
print(type(name))
print(type(age))
print(type(height))
print(type(cgpa))

# Comments

# uses single-line comment
height = 98 # height of the apartment
width = 72  # width of the apartment

# uses multi-line comment
'''
The height is 98 and
the width is 72 of
the department

'''

# Use a module to print all Python keywords.
#  Count total number of keywords.

import keyword
print("List of python keywords")
print(keyword.kwlist)

print("Total no of keywords is",len(keyword.kwlist))

# Create one variable of boolean
a = True
b = False
print(a)
print(b)

# literals practice

# Numeric literal
num = 100

# String literal
text = "Hello Python"

# Boolean literal
status = True

# List literal
fruits = ["apple", "banana", "mango"]

# Tuple literal
colors = ("red", "blue", "green")

# Printing all literals
print("Numeric Literal:", num)
print("String Literal:", text)
print("Boolean Literal:", status)
print("List Literal:", fruits)
print("Tuple Literal:", colors)

# Type Conversion Challenge
num="250"
price=99.99

# string → int
int_num=int(num)
print(type(int_num))
# string → float
float_val=float(num)
print(type(float_val))
# float → int
int_val=int(price)
print(type(int_val))

