# -*- coding: utf-8 -*-
"""Day_2_operators and conditional_statements.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lW0XpYIYWa28esTitKm1b0gI8rx5sOU8

# Operators and Conditional statements
"""

# Write a program to input two numbers and perform Addition, Subtraction, Multiplication, Division, and Modulus
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

print("Addition =", a + b)
print("Subtraction =", a - b)
print("Multiplication =", a * b)
print("Division =", a / b)
print("Modulus =", a % b)

# Write a program to swap two numbers using arithmetic operators (without using a third variable
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))

a,b=b,a
print("After swapping:")
print("a =", a)
print("b =", b)

# Write a program to find whether a given number is even or odd using the % operator
num = int(input("Enter a number: "))

if num % 2 == 0:
    print("Even Number")
else:
    print("Odd Number")

# Write a program to calculate the area and perimeter of a rectangle using operators
length = int(input("Enter length: "))
breadth = int(input("Enter breadth: "))

area = length * breadth
perimeter = 2 * (length + breadth)

print("Area =", area)
print("Perimeter =", perimeter)

# Write a program to convert temperature from Celsius to Fahrenheit
celsius = float(input("Enter temperature in Celsius: "))

fahrenheit = (9/5) * celsius + 32

print("Temperature in Fahrenheit =", fahrenheit)

# Write a program to calculate simple interest
p = int(input("Enter first number: "))
r = int(input("Enter second number: "))
t = int(input("Enter third number: "))

si = (p * r * t) / 100

print("Simple Interest =", si)

# Write a program to calculate the average of 5 numbers using arithmetic operators.
a = int(input("Enter first number: "))
b = int(input("Enter first number: "))
c = int(input("Enter first number: "))
d = int(input("Enter first number: "))
e = int(input("Enter first number: "))
average=a+b+c+d+e/5
print(average)

# Write a program to find the square, cube, and square root of a number
num = int(input("enter a number:"))
square=num**2
cube=num**3
square_root=0.5*num
print(square)
print(cube)
print(square_root)

# Write a program to calculate the total number of days from years, months, and days entered by the user
years = int(input("Enter years: "))
months = int(input("Enter months: "))
days = int(input("Enter days: "))

total_days = (years * 365) + (months * 30) + days

print("Total days: ", total_days)

# Write a program to demonstrate the use of relational and logical operators
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
# relational operators
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)
print(a == b)
print(a != b)
# logical operators
print(a > b and a < b)
print(a > b or a < b)
print(not(a > b))



"""# Conditional Statements"""

# Write a program to check whether a number is positive, negative, or zero
num = int(input("Enter a number: "))

if num > 0:
    print("Positive Number")
elif num < 0:
    print("Negative Number")
else:
    print("Zero")

# Write a program to find the largest of two numbers
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
if a>b:
  print("a is greater",a)
else:
  print("b is greater",b)

# Write a program to find the largest of three numbers using nested if
num1 = int(input("Enter first number: "))
num2 = int(input("Enter second number: "))
num3 = int(input("Enter third number: "))
if num1>num2 and num1>num3:
  print("num1 is greater",num1)
elif num2>num1 and num2>num3:
  print("num2 is graeter",num2)
elif num3>num1 and num3>num2:
  print("num3 is greater",num3)
else:
  print("Invalid value5")

# Write a program to check whether a year is a leap year or not
year=int(input('Enter a year:'))

if (year % 400 == 0) or (year % 4 == 0 and year % 100 != 0):
    print(year, "is a Leap Year")
else:
    print(year, "is not a Leap Year")

age = int(input("Enter the age:"))
if age>18:
  print("person is not aligible to vote")
else:
  print("The person is eligible to vote")

# Write a program to assign grades based on marks
marks = int(input("enter the mark"))
if marks>=90:
  print("Grade A")
elif marks >= 75:
  print("Grade B")
elif marks >= 60:
  print("Grade C")
elif marks >= 50:
  print("Grade D")
else:
  print("Grade E")

# Write a program to check whether a given number is divisible by both 5 and 11
num = int(input("Enter a number: "))

if num % 5 == 0 and num % 11 == 0:
    print("Divisible by both 5 and 11")
else:
    print("Not divisible by both 5 and 11")

# Write a program to input three sides of a triangle and determine whether the triangle is:
# Equilateral
# Isosceles
# Scalene
a = int(input("Enter first side: "))
b = int(input("Enter second side: "))
c = int(input("Enter third side: "))
if a==b==c:
  print("It is a equatorial traingle")
elif a==b and a==c and b==c:
  print("It is a isosceles traingle")
else:
  print("It is a scalene traingle")

