# -*- coding: utf-8 -*-
"""Python_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E-_Dtwblq60r7wVmYRUuxQvAX35AlTrL

# Python Day_2: Loops in  [For Loop]
"""

# Print numbers from 1 to 10
for i in range(1,11):
  print(i)

# Print even numbers from 1 to 20
for i in range(1,20):
  if i%2==0:
    print("Numbers are even",i)

# Print odd numbers from 1 to 15
for i in range(1,16):
  if i%2!=0:
    print('Numbers are odd',i)

# Print the multiplication table of a number.
num=int(input("enter a number:"))
for i in range(1,11):
  print(num,'*',i,'=',num*i)

# Find the sum of numbers from 1 to n
n = int(input("Enter the value of n"))
sum = 0
for i in  range(1,n+1):
  sum = sum+i
print("sum=",sum)

# Print numbers from 20 to 1.
for i in range(20,1,-1):
  print(i)

# Print squares of numbers from 1 to 10
for i in range(1,11):
  print(f"{i}*{i}={i*i}")

# Print cubes of numbers from 1 to 10
for i in range(1,11):
  print(f"{i}*{i}*{i}={i*i*i}")

# Print all numbers divisible by 5 between 1 and 100
for i in range(1,100):
  if i%5==0:
    print(i)

# Print all numbers divisible by both 3 and 5
for  i in range(1,100):
  if i%3==0 and i%5==0:
    print(i)

# Find the sum of all even numbers from 1 to n
n = int(input("enter a number:"))
sum=0
for i in range(1,n+1):
    if i%2==0:
       sum=sum+i

print("The sum of all even numbers is",sum)

# Count how many numbers are between 1 and n
n = int(input("enter a number:"))
count=0
for i in range(1,n+1):
    count=count+i
print("count=",count)

# Find the sum of squares from 1 to n
n=int(input("enter anumber:"))
sum=0

for i in range(1,n+1):
  sum=sum+(i*i)
print("The sqaures of the numbers is",sum)

# Calculate the average of n numbers entered by the user
n=int(input("enter anumber:"))
sum=0

for i in range(n):
  num=int(input("enter a number:"))
  sum=sum+num
avg=sum/n
print("The avergae of numbers is",avg)

# Check whether a number is an Armstrong number

# Print all prime numbers from 1 to 100

# Check whether a number is a Perfect Number